In [64]:
import pandas as pd

# Preprocesamiento de datos

In [50]:
df = pd.read_csv('data/departamentos.csv')

df['precio'] = df['precio'].astype(float)
df['gastos_comunes'] = df['gastos_comunes'].astype(float)

# Precio total
df['total'] = df['precio'] + df['gastos_comunes']
# subconjunto de datos con total menor a 600000
df = df.loc[(df['total'] <= 600000)]

# Analisis Exploratorio de Datos

In [51]:
df.shape

(271, 19)

In [52]:
df.head()

,preferencia,titulo,comuna,estacion_cercana,distancia_estacion,dormitorios,baños,estacionamientos,bodegas,superficie_total,superficie_util,currency_symbol,precio,gastos_comunes,search_gc,descripcion,ubicacion,url,total
2,0,Dpto. Peñalolen - Jose Arrieta,La Reina,Fernando Castillo Velasco,1433.0,2.0,1.0,NaN,NaN,45.0,45.0,$,370000.0,5000.0,0,departamento ubicado en jose arrieta con ictin...,"José Arrieta 6855, Penalolen, Peñalolén, Chile...",https://www.portalinmobiliario.com/MLC-9860745...,375000.0
9,0,Departamento Estudio De Un Ambiente,La Reina,Simón Bolívar,485.0,1.0,1.0,1.0,NaN,24.0,18.0,$,380000.0,0.0,0,depto amoblado bien ubicado cerca de metro pla...,"Avenida Simón Bolívar 5700 - 6000, La Reina, C...",https://www.portalinmobiliario.com/MLC-9742086...,380000.0
25,0,Cómodo Departamento A Pasos Estación Metro Vic...,La Florida,Rojas Magallanes,462.0,2.0,2.0,1.0,1.0,65.0,60.0,$,450000.0,90000.0,0,amplio y luminoso departamento ubicado en piso...,"Vicuña Mackenna, La Florida, Puente Alto, Chil...",https://www.portalinmobiliario.com/MLC-9866173...,540000.0
27,0,Muy Lindo Depto De 2 Dorm La Florida,La Florida,Vicente Valdés,70.0,2.0,1.0,1.0,NaN,58.0,56.0,$,450000.0,55000.0,0,dep 2 dorm la florida muy cerca del mall cocin...,"Vicuña Mackenna 7801, La Florida, Chile, Vicen...",https://www.portalinmobiliario.com/MLC-9846176...,505000.0
28,0,Departamento En Arriendo De 3 Dorm. En La Florida,La Florida,Los Quillayes,835.0,3.0,1.0,NaN,NaN,55.0,55.0,$,380000.0,25000.0,0,arriendo departamento la florida excelente ubi...,"San Jorge/san Pablo, Los Quillayes, La Florida...",https://www.portalinmobiliario.com/MLC-9866081...,405000.0

In [53]:
df.dtypes

preferencia             int64
titulo                 object
comuna                 object
estacion_cercana       object
distancia_estacion    float64
dormitorios           float64
baños                 float64
estacionamientos      float64
bodegas               float64
superficie_total      float64
superficie_util       float64
currency_symbol        object
precio                float64
gastos_comunes        float64
search_gc               int64
descripcion            object
ubicacion              object
url                    object
total                 float64
dtype: object

In [54]:
df[df.columns[~df.columns.isin(['preferencia', 'search_gc'])]].describe()

,distancia_estacion,dormitorios,baños,estacionamientos,bodegas,superficie_total,superficie_util,precio,gastos_comunes,total
count,210.000000,270.000000,270.000000,173.000000,95.0,267.000000,266.000000,271.000000,271.000000,271.000000
mean,551.242857,1.444444,1.277778,1.161850,1.0,46.166779,43.517932,453718.623616,60240.531365,513959.154982
std,406.006827,0.593229,0.684851,2.053738,0.0,12.770277,12.852111,62564.894552,25448.965238,69778.369374
min,46.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,190000.000000,0.000000,245000.000000
25%,270.250000,1.000000,1.000000,1.000000,1.0,37.000000,35.000000,420000.000000,50000.000000,480000.000000
50%,430.500000,1.000000,1.000000,1.000000,1.0,45.000000,42.000000,456906.000000,60000.000000,530000.000000
75%,703.000000,2.000000,1.000000,1.000000,1.0,55.000000,52.000000,500000.000000,75000.000000,567323.500000
max,1937.000000,3.000000,10.000000,28.000000,1.0,80.000000,80.000000,600000.000000,120000.000000,600000.000000

In [55]:
df[df.columns[~df.columns.isin(['titulo','currency_symbol','descripcion','ubicacion','url'])]].describe(include = ['O'])

       comuna estacion_cercana
count     271              210
unique      8               43
top     Ñuñoa      Irarrázaval
freq      102               18

In [62]:
df.groupby(['comuna'])['comuna'].count().sort_values(ascending=False)

comuna
Ñuñoa                 102
Macul                  82
Providencia            47
Las Condes             20
La Florida              9
Peñalolén               6
La Reina                3
RM (Metropolitana)      2
Name: comuna, dtype: int64

In [61]:
df.groupby(['estacion_cercana'])['estacion_cercana'].count().sort_values(ascending=False).head(10)

estacion_cercana
Irarrázaval            18
Estadio Nacional       13
Las Torres             13
Macul                  12
Chile España           12
Villa Frei             11
Rodrigo de Araya       11
Quilín                  9
Monseñor Eyzaguirre     9
Los Leones              8
Name: estacion_cercana, dtype: int64